[[language]]
name = "php"
language-servers = [ "intelephense", "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true

[[language]]
name = "html"
language-servers = [ "tailwindcss-ls", "vscode-html-language-server" ]

[[language]]
name = "elixir"
language-id = "elixir"
language-servers = [ "elixir-ls" ]
auto-format = true

[[language]]
name = "heex"
language-id = "phoenix-heex"
language-servers = [ "elixir-ls", "tailwindcss-ls", "vscode-html-language-server" ]
auto-format = true

[language-server.intelephense.config]
intelephense.diagnostics.undefinedProperties = false

# *** If you have issues with heex files, try this
#
# [[language-server]]
# tailwindcss-ls-ex = { command = "tailwindcss-language-server", args = ["--stdio"], config = { tailwindCSS = { includeLanguages = { "elixir" = "html"}} } }

# [[language]]
# name = "elixir"
# auto-format = true
# language-servers = ["elixir-ls", "tailwindcss-ls-ex"]

# [[language]]
# name = "heex"
# auto-format = true
# language-id = "phoenix-heex"
# language-servers = ["elixir-ls", "tailwindcss-ls-ex"]
